### ISSUE TITLE
cross-self attention

### ISSUE THREAD

**Issue by aunusualman** [ChinaYi/ASFormer#1]
您好，在您提供的decoder代码中，V 是来自上一个decoder或者encoder的feature, Q 和K利用的x1，即上一层的输出，是不是和论文中描述的不一样？

**Comment by ChinaYi** [comment]
啊你说的没错，这是做实验的时候产生的遗留问题，我们使用的应该是代码中的版本，但是两者的结果应该差不多。而且出发点也接近，都是利用encoder的feature来指导decoder的修正，所以当时可能忽略了。考虑到代码和论文的一致性，我会在近期更新arxiv版本~谢谢你的发现
