### ISSUE TITLE
about  the randomness of code

### ISSUE THREAD

**Issue by wlsh1up** [ChinaYi/ASFormer#10]
Hi, Thank you for your code
https://github.com/ChinaYi/ASFormer/blob/3940443a7dca336f879c43a42bcf91c5bf7c790f/model.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L370
When I change the test interval from 10 to 20, 30, etc., different results(such as training loss ) are obtained under the same seed. What do you think is the reason？
best regards

**Comment by ChinaYi** [comment]
Each test operation will call reset() function, see https://github.com/ChinaYi/ASFormer/blob/3940443a7dca336f879c43a42bcf91c5bf7c790f/model.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L393

where reset function will call random() function, which results different randomness even started with the same seed.
https://github.com/ChinaYi/ASFormer/blob/3940443a7dca336f879c43a42bcf91c5bf7c790f/batch_gen.py#L21-L47
