### ISSUE TITLE
Feature Extraction 

### ISSUE THREAD

**Issue by Camillo4eyes** [ChinaYi/ASFormer#12]
Hi, can you provide more informations about the feature extraction? I would like to use this fantastic model on my dataset but I don't know how to extract the features to feed to the encoder.

**Comment by ChinaYi** [comment]
We used the pretrained I3D model on Kinetics.  Then we used a window of size 21 around each frame, i.e. [t-10, t+10] to extract frame-wise features.  For more details about the features please check this repo https://github.com/ahsaniqbal/Kinetics-FeatureExtractor

**Comment by Camillo4eyes** [comment]
So, considering a stack size (or window size) of 21, the extracted features will have size (n_frames / 21) x 1024, right? (which then, by concatenating the stram RGB and flow will become (n_frames / 64) * 2048). Didn't you use any step between one window and another? Sorry for the many questions, but I'm really curious and I really want to use this model!

**Comment by ChinaYi** [comment]
Sorry for my late response :) really got some busy days.   We do not use any step between windows since we have to collect features per-frame with full fps rate.
