### ISSUE TITLE
How to understand stage images from result

### ISSUE THREAD

**Issue by TikaToka** [ChinaYi/ASFormer#15]
Hello, thank you for sharing your amazing work!.

I have a question when analysing the results.

for images generated like below
![image](https://user-images.githubusercontent.com/49054667/215708234-123f18dd-90c6-4989-9c6f-b64fdea6b3fb.png)

What does each row means? and what does each stage 0, 1, 2, 3 means?

Also, as the methods uses each frame's action label to evaluate, you might compare the model with action recognition models too. Is there any specific reason for not comparing result for action recognition?

Thank you in advance!

**Comment by basavaraj-hampiholi** [comment]
Hi @TikaToka @ChinaYi 

1. Each row with a color bar represents a complete activity. And each color segment represents a particular action segment.
2. Action segmentation task requires several evaluation metrics such as Framewise Accuracy (FA), Edit Score, and F1-scores. You can use the FA metric to perform a comparison with the action recognition task.

I hope this is helpful for you.

**Comment by laohuijiadezhu** [comment]
Hi, @basavaraj-hampiholi @ChinaYi 
There are three sub-lines in the picture. I have 3 questions.

1. What is the difference between the first line and the second line? 
2. What does the third line mean?
3. What does each stage 0, 1, 2, 3 means?

Thank you in advance!

**Comment by basavaraj-hampiholi** [comment]
@TikaToka 
I am not sure how you generated this figure. But the first color bar could represent the ground truth sequence and the second color bar could represent the predicted sequence. I am not sure about the third line.

Stage 0,1,2,3 refer to the multiple stages used for iterative refinement. You can refer to this work
https://github.com/yabufarha/ms-tcn

**Comment by laohuijiadezhu** [comment]
Thank you for your reply! @basavaraj-hampiholi 
I think this figure is generated by executing scripts in this repository. I also got the same picture, so I have the same doubt. According to the source code, the first two bars seem to be the result of the model. One is confidence, the other is prediction.
[segment_bars_with_confidence(results_dir + '/{}_stage{}.png'.format(vid, i),](https://github.com/ChinaYi/ASFormer/blob/e1bbe4f3ed083748f91467c51a63ac2a8b9277ad/model.py#L424)

**Comment by TikaToka** [comment]
@basavaraj-hampiholi  Thank you for your reply!
as @laohuijiadezhu mentioned, I've generated by executing scripts given.
`python main.py --action=predict --dataset=50salads/gtea/breakfast --split=1/2/3/4/5`

**Comment by basavaraj-hampiholi** [comment]
Hi @laohuijiadezhu @TikaToka,

The top color bar represents the ground truth sequence. The second color bar represents the predicted scores from the network. At the bottom, the line shows the top softmax probabilities. Note that the line is getting smoother at every subsequent stage. This shows that the predictions are refined over stages.

Check the function  **segment_bars_with_confidence** from eval.py
