### ISSUE TITLE
flops，GPU mem code

### ISSUE THREAD

**Issue by txyxju1997** [ChinaYi/ASFormer#3]
作者您好：感谢您做出的系列贡献，我想请教的是您论文部分Table9计算prams flops和GPU mem这里的代码可否方便分享一下，不知如何求得flops大小，谢谢！

**Comment by ChinaYi** [comment]
GPU Mem的话跑程序的时候记录一下GPU Mem花费的最大值就行。
Flops 我用的是thop （pip install thop）, 使用方式十分简单，几行代码自定义一个输出测一下就行，具体的代码我没有留存了。

**Comment by txyxju1997** [comment]
我也用的thop进行测试， 我输入的是一个feature特征，但是报错总说TypeError: forward() missing 1 required positional argument: 'mask'，所以我不太清楚哪里有问题。
        input = torch.tensor([1,64,4244])
        flops,params = profile(self.model, (input,))
        print(flops)
        print(params)

**Comment by ChinaYi** [comment]
模型的输入还需要一个mask参数，而且你input生成的方法也有问题, 你可以这样:
input, mask = torch.randn(1, 2048, 4244), torch.ones(1,4244)  # 生成一个长度为4244的输入
flops, params = profile(self.model, (input,mask,))
print(flops)
print(params)

**Comment by txyxju1997** [comment]
谢谢您的帮助，mask问题解决了，但是按照您的代码运行后还是会有一点小问题：IndexError: too many indices for tensor of dimension 2
