### ISSUE TITLE
Batch size constraint

### ISSUE THREAD

**Issue by OliverGuy** [ChinaYi/ASFormer#5]
Hello,

Thank you for your amazing work !

I was wondering if there is any particular reason for imposing a batch size of 1 in `model.py`: https://github.com/ChinaYi/ASFormer/blob/89e72d840a3d3eb8f16c270adb5031d648d9fb73/model.py#L138

In my testing, ASFormer learns fine with bigger batch sizes.

**Comment by ChinaYi** [comment]
Hi~ There is no particular reason for imposing a batch size of 1. 
At the beginning of the project, the window size needs to be adjusted frequently,  the large batch size can easily got out-of-memory error in the middle of training process. So, I just set the batch size equals 1 for  convenience.  And I do not conduct ablation study about the batch size in the subsequent experiments.  I am glad that you found the larger batch size works well too.

**Comment by OliverGuy** [comment]
Good to know, thank you for your answer !

**Comment by wlsh1up** [comment]
Hi, I use batch size 1 for split, get the result
(s1)[83.40807175 81.16591928 72.19730942]  76.414887(edit) 82.9062(Acc)
However, change batch size to 8 and lr 0.001,  the result is not good.
(s1) [79.8245614  77.19298246 69.73684211]  74.948214 83.1072
you mentioned ASFormer learns fine with bigger batchsize, Have you made any other changes？

**Comment by arthur-cahu** [comment]
Hi, I used it on another dataset and application (for temporal sign segmentation), so that might explain why our results are different.

**Comment by OliverGuy** [comment]
Hi, I used it on another dataset and application (for temporal sign segmentation), so that might explain why our results are different.

**Comment by wlsh1up** [comment]
Thank you very much for your reply. Increasing the batchsize still cannot be reproduced with more epoch. 

Do you have any ways to speed up model training? such us decrease sample rate ?  Training Breakfast Dataset is too slow

**Comment by ChinaYi** [comment]
Hi, sorry for my late response. Just update the README file since there is a little bug in the code. I don't know if it will have an impact with large batch_size, maybe you can have a try.  As for the breakfast dataset, you may also need to decrease the number of layers while reducing the sampling rate.
