### ISSUE TITLE
Cannot download the model 

### ISSUE THREAD

**Issue by madmoiselleve** [ChinaYi/ASFormer#6]
Hi ! 
Firstly, thanks for sharing this repo ! I'm struggling to download the model (3. Download the pre-trained models at (https://pan.baidu.com/s/1zf-d-7eYqK-IxroBKTxDfg)) Indeed, the site says that you need to create an account to download the file. The thing is I cannot create an account with a french phone number 😅  Any other way to download the pretrained model ? 
Many thanks !

**Comment by ChinaYi** [comment]
Update the link https://drive.google.com/file/d/1xNykN3vXMHCpHIYT0eb5ZHnKSu3Y2K8r/view?usp=sharing

**Comment by madmoiselleve** [comment]
Many thanks !
