### ISSUE TITLE
pre-extracted feature

### ISSUE THREAD

**Issue by SISTMrL** [ChinaYi/ASFormer#7]
你好，我最近也在研究一个类似的任务，看到你的这篇文章很感兴趣，打算借鉴下。请问下，论文里提到的pre-extract feature指的是每帧图像提取出来的feature map吗，能详细阐述下吗？谢谢

**Comment by ChinaYi** [comment]
用在kinetics数据集上训练的I3D模型提取的特征，每一帧的特征为2048-d.
