### ISSUE TITLE
results on salads50 does not match table 5

### ISSUE THREAD

**Issue by seyeeet** [ChinaYi/ASFormer#8]
Hi thanks for your work.
I was able to train and test the model and achieve similar performance as mentioned in the paper when I use both enc and dec. However, when I don't use the decoder, the results are much worse than what is mentioned in the table 5 (first row).
I was wondering if I need to do any changes to the setting to get the same performance (specially for Acc)?
I notice that without using the decoder the acc drops lower than 80.

**Comment by ChinaYi** [comment]
Learning rates may matter. Have you tried smaller lr such as 0.0001 or larger lr such as 0.001 ?

**Comment by seyeeet** [comment]
I tried 0.001 but still not good, do you have a suggestion for that if you know what lr should I use?

**Comment by ChinaYi** [comment]
The parameters used for table 5 have not been changed. But I think smaller lr might help, such as 0.0001.
