### ISSUE TITLE
Increase the batchsize and the result is hurt

### ISSUE THREAD

**Issue by wlsh1up** [ChinaYi/ASFormer#9]
Hi, 
Thank you for your work.
When I try to increase the batch size, the index drops a lot. What do you think are the possible reasons

the GPU is A100 40g.

train with default setting, only split 1
> (s1)[83.40807175 81.16591928 72.19730942]  75.934108  83.2241

just change batch size to 8 lr 0.001 and then train

> (s1)[68.94977169 67.57990868 55.25114155]  63.931922 72.0049

**Comment by ChinaYi** [comment]
I haven't tried such a big batch size :) . My suggestion is keep the lr to 5e-4, but train the model with larger epochs, say 300. The lr  of 1e-3 is too large to train self-att.

**Comment by ChinaYi** [comment]
[similar issues] (https://github.com/ChinaYi/ASFormer/issues/5)
